#!/usr/bin/env python3
"""
Data Accumulator — merges all training data sources into a unified dataset.

══════════════════════════════════════════════════════════════════════════════
Paper 2: Self-Healing Test Automation via ML-Enhanced Locator Recovery
         Vijay P. Javvadi — 2024-2026
══════════════════════════════════════════════════════════════════════════════

Combines training data from three sources:
  1. Experiment-derived data  (data/training/healing_training_data.csv)
     — Generated by extract_training_data.py from heuristic experiment runs
  2. Real-time heal events    (data/heal_events/heal_events.csv)
     — Logged by HealEventLogger during live/experiment runs
  3. Production heal events   (data/production/heal_events_*.csv)
     — Imported from deployed services (any CSV matching the schema)

Output:
  data/training/accumulated_training_data.csv   (deduplicated, labeled)
  data/training/accumulation_report.json        (stats on each source)

Usage:
  python scripts/accumulate_training_data.py
  python scripts/accumulate_training_data.py --min-events 1000  # require minimum
  python scripts/accumulate_training_data.py --retrain          # accumulate + retrain
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

from extract_training_data import FEATURE_COLUMNS

LABEL_COL = "label"
REQUIRED_COLS = FEATURE_COLUMNS + [LABEL_COL]


def load_csv(path: Path) -> "pd.DataFrame | None":
    """Load a CSV if it exists and has the required columns."""
    import pandas as pd

    if not path.exists():
        return None

    df = pd.read_csv(path)
    missing = [c for c in REQUIRED_COLS if c not in df.columns]
    if missing:
        print(f"  [SKIP] {path.name}: missing columns {missing}")
        return None

    # Keep only feature columns + label
    df = df[REQUIRED_COLS].copy()
    df[LABEL_COL] = df[LABEL_COL].astype(int)

    return df


def accumulate(min_events: int = 0) -> dict:
    """Merge all training data sources."""
    import pandas as pd

    report = {"sources": [], "total_before_dedup": 0, "total_after_dedup": 0}
    frames = []

    # ── Source 1: Experiment-derived data ─────────────────────────────────
    exp_path = PROJECT_ROOT / "data" / "training" / "healing_training_data.csv"
    exp_df = load_csv(exp_path)
    if exp_df is not None:
        n = len(exp_df)
        n_pos = exp_df[LABEL_COL].sum()
        print(f"  ✓ Experiment data: {n:,} rows ({n_pos:,} positive)")
        frames.append(exp_df)
        report["sources"].append({
            "name": "experiment", "path": str(exp_path),
            "rows": n, "positive": int(n_pos),
        })
    else:
        print(f"  ✗ Experiment data: not found ({exp_path})")

    # ── Source 2: Real-time heal events ──────────────────────────────────
    rt_path = PROJECT_ROOT / "data" / "heal_events" / "heal_events.csv"
    rt_df = load_csv(rt_path)
    if rt_df is not None:
        n = len(rt_df)
        n_pos = rt_df[LABEL_COL].sum()
        print(f"  ✓ Real-time events: {n:,} rows ({n_pos:,} positive)")
        frames.append(rt_df)
        report["sources"].append({
            "name": "realtime", "path": str(rt_path),
            "rows": n, "positive": int(n_pos),
        })
    else:
        print(f"  ✗ Real-time events: not found ({rt_path})")

    # ── Source 3: Production imports ─────────────────────────────────────
    prod_dir = PROJECT_ROOT / "data" / "production"
    if prod_dir.exists():
        for csv_file in sorted(prod_dir.glob("heal_events_*.csv")):
            prod_df = load_csv(csv_file)
            if prod_df is not None:
                n = len(prod_df)
                n_pos = prod_df[LABEL_COL].sum()
                print(f"  ✓ Production [{csv_file.name}]: {n:,} rows ({n_pos:,} positive)")
                frames.append(prod_df)
                report["sources"].append({
                    "name": f"production/{csv_file.name}",
                    "path": str(csv_file),
                    "rows": n, "positive": int(n_pos),
                })
    else:
        print(f"  ✗ Production directory: not found ({prod_dir})")

    if not frames:
        print("\n[ERROR] No training data found from any source.")
        sys.exit(1)

    # ── Merge and deduplicate ────────────────────────────────────────────
    combined = pd.concat(frames, ignore_index=True)
    report["total_before_dedup"] = len(combined)

    # Deduplicate: same feature vector → keep latest (last occurrence)
    combined = combined.drop_duplicates(subset=FEATURE_COLUMNS, keep="last")
    report["total_after_dedup"] = len(combined)

    n_pos = combined[LABEL_COL].sum()
    n_neg = len(combined) - n_pos
    ratio = n_neg / n_pos if n_pos > 0 else float("inf")

    print(f"\n  Combined: {len(combined):,} rows (deduped from {report['total_before_dedup']:,})")
    print(f"  Positive: {n_pos:,} | Negative: {n_neg:,} | Ratio: 1:{ratio:.1f}")

    report["positive"] = int(n_pos)
    report["negative"] = int(n_neg)
    report["imbalance_ratio"] = round(ratio, 2)

    if min_events > 0 and len(combined) < min_events:
        print(f"\n[WARN] Only {len(combined)} events, below minimum {min_events}. "
              f"Need {min_events - len(combined)} more events before retraining.")
        report["meets_minimum"] = False
    else:
        report["meets_minimum"] = True

    # ── Save ─────────────────────────────────────────────────────────────
    output_path = PROJECT_ROOT / "data" / "training" / "accumulated_training_data.csv"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    combined.to_csv(output_path, index=False)
    print(f"\n  Saved to {output_path}")

    report_path = PROJECT_ROOT / "data" / "training" / "accumulation_report.json"
    report_path.write_text(json.dumps(report, indent=2))
    print(f"  Report saved to {report_path}")

    return report


def main():
    parser = argparse.ArgumentParser(description="Accumulate training data from all sources.")
    parser.add_argument("--min-events", type=int, default=0,
                       help="Minimum events required before allowing retrain.")
    parser.add_argument("--retrain", action="store_true",
                       help="After accumulating, retrain the model on the new dataset.")
    parser.add_argument("--algorithm", choices=["gradient_boosting", "xgboost"],
                       default="gradient_boosting", help="ML algorithm for retraining.")
    args = parser.parse_args()

    print("=" * 60)
    print("  Training Data Accumulator")
    print("=" * 60)

    report = accumulate(min_events=args.min_events)

    if args.retrain and report["meets_minimum"]:
        print("\n" + "=" * 60)
        print("  Retraining model on accumulated data...")
        print("=" * 60)

        accumulated_path = PROJECT_ROOT / "data" / "training" / "accumulated_training_data.csv"
        cmd = [
            sys.executable, str(PROJECT_ROOT / "scripts" / "train_healing_model.py"),
            "--data", str(accumulated_path),
            "--algorithm", args.algorithm,
        ]
        print(f"  Running: {' '.join(cmd)}")
        result = subprocess.run(cmd, cwd=str(PROJECT_ROOT))

        if result.returncode == 0:
            print("\n  ★ Model retrained successfully on accumulated data.")
        else:
            print(f"\n  [ERROR] Retraining failed with exit code {result.returncode}")
    elif args.retrain and not report["meets_minimum"]:
        print(f"\n  [SKIP] Not retraining: below minimum event threshold.")

    print("\nAccumulation complete.")


if __name__ == "__main__":
    main()
